### ISSUE TITLE
Infografía - Gestion de proyectos de software

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-KarlaV0#2]
[T1_GP_Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-KarlaV0/files/12534097/T1_GP_Infografia.pdf)

**Comment by MLR062998** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
